<?php

# Prevent direct access
if (!defined('ABSPATH')) die('Error!');

# define icons
$appreplicaicons = array(

array("500px",0),
array("behance",0),
array("deezer",0),
array("facebook",0),
array("flickr",0),
array("instagram",0),
array("itunes",0),
array("pinterest",0),
array("socialfeed",0),
array("soundcloud",0),
array("smugmug",0),
array("spotify",0),
array("tumblr",0),
array("twitter",0),
array("vimeo",0),
array("youtube",0),

array("500px",1),
array("behance",1),
array("facebook",1),
array("flickr",1),
array("googleplus",1),
array("instagram",1),
array("itunes",1),
array("linkedin",1),
array("pinterest",1),
array("podcast",1),
array("rss",1),
array("soundcloud",1),
array("spotify",1),
array("tumblr",1),
array("twitter",1),
array("vimeo",1),
array("vine",1),
array("youtube",1),

array("500px",2),
array("behance",2),
array("facebook",2),
array("flickr",2),
array("googleplus",2),
array("instagram",2),
array("itunes",2),
array("linkedin",2),
array("pinterest",2),
array("podcast",2),
array("rss",2),
array("soundcloud",2),
array("spotify",2),
array("tumblr",2),
array("twitter",2),
array("vimeo",2),
array("vine",2),
array("youtube",2),

array("500px",3),
array("behance",3),
array("facebook",3),
array("flickr",3),
array("googleplus",3),
array("instagram",3),
array("itunes",3),
array("linkedin",3),
array("pinterest",3),
array("podcast",3),
array("rss",3),
array("soundcloud",3),
array("spotify",3),
array("tumblr",3),
array("twitter",3),
array("vimeo",3),
array("vine",3),
array("youtube",3),


array("500px",99),
array("apple",99),
array("behance",99),
array("behance-square",99),
array("deviantart",99),
array("dribbble",99),
array("facebook",99),
array("facebook-official",99),
array("facebook-square",99),
array("flickr",99),
array("foursquare",99),
array("google-plus",99),
array("google-plus-square",99),
array("instagram",99),
array("linkedin",99),
array("linkedin-square",99),
array("medium",99),
array("music",99),
array("pinterest",99),
array("pinterest-p",99),
array("pinterest-square",99),
array("rss",99),
array("rss-square",99),
array("slideshare",99),
array("soundcloud",99),
array("spotify",99),
array("tumblr",99),
array("tumblr-square",99),
array("twitter",99),
array("twitter-square",99),
array("vimeo",99),
array("vimeo-square",99),
array("vine",99),
array("youtube",99),
array("youtube-play",99),
array("youtube-square",99)

);
?>
 